### PR TITLE
Use Microsoft.Extensions.Logging replace Common.Logging

### PR DESCRIPTION
**Pull request by Cricle**
Removed NET452 support

### CODE REVIEW

**Comment by Cricle** [comment]
I have been push a [package](https://www.nuget.org/packages/MSLog.Quartz.Spi.MongoDbJobStore) to nuget, if this PR states merge or dealt or other thinks, i will delete the package.

**Comment by joesdu** [comment]
> I have been push a [package](https://www.nuget.org/packages/MSLog.Quartz.Spi.MongoDbJobStore) to nuget, if this PR states merge or dealt or other thinks, i will delete the package.

有个问题想请教下,使用这个包后,运行程序就会抛出一个异常,实在是不知道怎么解决了🥲
image

**Comment by Cricle** [comment]
> > I have been push a [package](https://www.nuget.org/packages/MSLog.Quartz.Spi.MongoDbJobStore) to nuget, if this PR states merge or dealt or other thinks, i will delete the package.
> 
> 
> 
> 有个问题想请教下,使用这个包后,运行程序就会抛出一个异常,实在是不知道怎么解决了🥲
> 
> image
> 
> 

这个要看看例子有强制性的初始化要求的，未来估计会移除掉

**Comment by joesdu** [comment]
> 
感觉Quartz官方也不给个文档怎么适配,我其实想用我自己的MongoDB封装的库,但是发现他不像IDS4那样方便,昨天晚上搞了一晚上,现在还是没搞定.我一会再研究下.

**Comment by glucaci** [comment]
Thanks, but this PR has more than only replacing the Common.Logging.
I've started a v4 branch, please if you want to contribute to a PR into the v4 branch to remote the Common.Logging.
Please let me know if you want to do it, otherwise i will do it.
Thanks!

**Pull request closed without merging**
