### PR TITLE
Make it work with Quartz 3.0.4

### PR DESCRIPTION
**Pull request by ghost**
Targeting .NET Framework 4.5.2, 4.6.2, and .NET Standard 2.0.

### CODE REVIEW

**Comment by chrisdrobison** [comment]
This is awesome! Thanks for the pull request. I've been meaning to work on this for some time. The only suggestion I have is that now that the job store is very asynchronous, a lot of those methods are returning Task.FromResult, making them synchronous calls. The Mongo driver is fully asynchronous now so I think it would be good to change the repository classes to async and take advantage of that all the way down to Mongo. Then you could just await everything instead of using Task.FromResult. Thoughts?

**Comment by ghost** [comment]
Hey thanks for such a quick response! I would be very open to that, but I don't really know how to proceed with chaining continuations and how that works in the face of exceptions. I have been going through and trying stuff like this:

```
        public Task<Calendar> GetCalendar(string calendarName, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Collection
                .FindAsync(calendar => calendar.Id == new CalendarId(calendarName, InstanceName))
                .ContinueWith(cursor => cursor.Result.FirstOrDefault(), TaskContinuationOptions.OnlyOnRanToCompletion);
        }
```

Does this work? Or is there a more robust way to be handling this? Also, sorry for breaking your CI, from the error message it looks like maybe it's not set up to use the .NET Core tooling yet? The reason we would like to use .NET Core is that is where my team's project is ultimately headed.

As a final note for transparency sake, I brought back a few things that Quartz 3.0.4 got rid of, including the ```QuartzThread``` (I don't know if that's needed or not), and the ```LogicalThreadContext```. The latter is problematic at the moment because upstream's implementation relies on the use of ```CallContext``` which in turn relies on remoting. Remoting as a whole has been removed from .NET Core with no alternatives. We found a blog post from Daniel Cazzulino [suggesting a workaround](http://www.cazzulino.com/callcontext-netstandard-netcore.html), which we are trying.

**Comment by chrisdrobison** [comment]
As for your first question, this is what it would look like:

```
        public async Task<Calendar> GetCalendar(string calendarName, CancellationToken cancellationToken = default(CancellationToken))
        {
            var calendars = await Collection
                .FindAsync(calendar => calendar.Id == new CalendarId(calendarName, InstanceName));
            return calendars.FirstOrDefault();
        }
```

As for your second question about bringing back old thing. The new Quartz should support .NET Core so I would suggest looking at their SQL data store implementation. I actually followed that very closely when creating this implementation.

**Comment by ghost** [comment]
Okay cool thanks! This part may take me a while, but hopefully I can get the rest of it async in the next few days?

**Comment by ghost** [comment]
Hey, just a quick update, I can still finish off the asyncing, but I will have to do it on personal time, not company time. Given that, my ETA would be more like a couple of weeks.

**Comment by dmumladze** [comment]
@chrisdrobison @AdrianCohea Can you get this merged in, what is stopping you?

**Comment by ghost** [comment]
@dmumladze @chrisdrobison Nothing in particular. I haven't been able to return to this to finish making everything use all of the asynchronous APIs as Chris requested. FWIW my company has been running this in production since April. We use Quartz for a number of things including retrying failed Stripe payments. So it's been battle-tested at least good enough for us to use it, but I'm not sure what your use case is.

**Comment by ghost** [comment]
I think as a standalone contribution it's "good enough." May not be perfect, but it's a bold step in a good direction. That said, there may be some problems since the AppVeyor integration Chris has does not appear to support the .NET Core toolchain. So that might be a "blocker" there.

**Comment by dmumladze** [comment]
@AdrianCohea Good to know as it give me the comfort for the upcoming prod release scheduled in few weeks. However, I'll hold off on .NET Standard and Quartz 3, since it is not ready and come back for later releases.. Thanks for all the work you've done!

**Comment by chrisdrobison** [comment]
I've started working on this pull request. Hopefully have something in the next couple of days.

**Pull request merged**
